services:
  - type: web
    name: retail-metabase
    runtime: docker
    dockerfilePath: ./infra/Dockerfile.metabase
    plan: free
    envVars:
      - key: MB_DB_TYPE
        value: postgres
      - key: MB_DB_CONNECTION_URI
        fromDatabase:
          name: metabase-db
          property: connectionString
      - key: MB_SITE_URL
        value: https://retail-metabase.onrender.com

databases:
  - name: metabase-db
    plan: free
