version: 2

models:
  - name: stg_orders
    description: Cleaned orders from raw source
    columns:
      - name: order_id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - not_null
      - name: order_status
        tests:
          - accepted_values:
              values: ['delivered','shipped','canceled','unavailable','invoiced','processing','created','approved']

  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: stg_payments
    columns:
      - name: order_id
        tests:
          - not_null
      - name: payment_value
        tests:
          - not_null

  - name: stg_products
    columns:
      - name: product_id
        tests:
          - unique
          - not_null

  - name: stg_sellers
    columns:
      - name: seller_id
        tests:
          - unique
          - not_null
